language: java
jdk:
- oraclejdk8
services:
- docker
before_install:
- docker pull redis:3.2.9
- docker run --name fmeng-redis -p 6379:6379 -d redis:3.2.9 redis-server --appendonly yes --requirepass "fmeng123"
script: mvn -B clean install -Dgpg.skip=true -Dmaven.test.skip=true